version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.IdentityModel.Logging
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.Protocols.OpenIdConnect
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.Azure.DocumentDB
    versions:
    - 2.13.1
  - dependency-name: Microsoft.Net.Compilers
    versions:
    - 3.8.0
  - dependency-name: Microsoft.Rest.ClientRuntime
    versions:
    - 2.3.22
  - dependency-name: Autofac
    versions:
    - 6.1.0
